{% set name = "graphrag" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/graphrag-{{ version }}.tar.gz
  sha256: 6d5e95c8ae5973c7d22e0538435fa634b23c0391182ddc1fc441fb8ff511e104

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10,<3.13
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning >=1.0.0,<2.0.0
    - pip
  run:
    - python >=3.10,<3.13
    - environs >=11.0.0,<12.0.0
    - datashaper >=0.0.49,<0.0.50
    - azure-search-documents >=11.4.0,<12.0.0
    - lancedb >=0.10.0,<0.11.0
    - uvloop >=0.19.0,<0.20.0
    - nest-asyncio >=1.6.0,<2.0.0
    - aiolimiter >=1.1.0,<2.0.0
    - aiofiles >=24.1.0,<25.0.0
    - openai >=1.35.7,<2.0.0
    - nltk 3.8.1
    - tiktoken >=0.7.0,<0.8.0
    - numba 0.60.0
    - numpy >=1.25.2,<2.0.0
    - graspologic >=3.4.1,<4.0.0
    - networkx >=3.0.0,<4.0.0
    - fastparquet >=2024.2.0,<2025.0.0
    - scipy 1.12.0
    - pyyaml >=6.0.1,<7.0.0
    - pyaml-env >=1.2.1,<2.0.0
    - python-dotenv >=1.0.0,<2.0.0
    - tenacity >=8.5.0,<9.0.0
    - swifter >=1.4.0,<2.0.0
    - pydantic >=2.0.0,<3.0.0
    - rich >=13.6.0,<14.0.0
    - textual >=0.72.0,<0.73.0
    - python-devtools >=0.12.2,<0.13.0
    - typing-extensions >=4.12.2,<5.0.0
    - azure-storage-blob >=12.19.0,<13.0.0
    - azure-identity >=1.17.1,<2.0.0

test:
  imports:
    - graphrag
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A modular graph-based Retrieval-Augmented Generation (RAG) system
  home: https://github.com/microsoft/graphrag
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
